[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [":openzeppelin-contracts/=lib/openzeppelin-contracts/"]
rpc_url = "https://sepolia.infura.io/v3/cdfcb5cf1f7b4953862dc9238a7d59e8"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
