[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
